fix: avoid spurious 'unable to clear' errors
In the case where we are not able to set a server breakpoint, for
example, when the file doesn't exist locally or is ambiguous, we are
emitted a spurious error in the log:
  Error: Unable to clear breakpoint in v8

This change detects the situation and aviods deleting a non-existent
breakpoint.