chore: update `teeny-request` (#589)
`teeny-request` needs to be updated to address the following
compiler error:
```
src/client/stackdriver/debug.ts:61:22 - error TS2352:
  Conversion of type 'typeof teenyRequest' to type
  'RequestAPI<Request, CoreOptions, RequiredUriUrl>' may be a
  mistake because neither type sufficiently overlaps with the
  other.  If this was intentional, convert the expression to
  'unknown' first.
    Property 'get' is missing in type 'typeof teenyRequest'.
```